[project]
name = "e-commerce"
version = "0.1.0"
description = ""
authors = [
    {name = "Rodion Ventslovsky",email = "vents_23@mail.ru"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest (>=8.4.2,<9.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.lint.dependencies]
black = "^25.9.0"
isort = "^7.0.0"
flake8 = "^7.3.0"
mypy = "^1.18.2"

[tool.black]
line-length = 119
target-version = ['py311']
include = '\.pyi?$'
extend-exclude = '''
/(
  # ...
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 119
known_first_party = ["your_package_name"]

